### PR TITLE
add maintainer

### PR DESCRIPTION
**Pull request by ocefpaf**

### CODE REVIEW

**Comment by jreback** [comment]
seems travis has not built this....odd

**Comment by ocefpaf** [comment]
> seems travis has not built this....odd

Unfortunately no :unamused: 

People are issue too many changes and `conda-smithy` and issuing dozen of re-renderings which clogs Travis-CI. Hopefully this will be sorted out at the weekend when the load is lower.

**Comment by jreback** [comment]
thanks

did you guys solve the dedupe or problem on Travis (iow pushing the same pr cancels the previous) which appveyor and circleci just do nicely

**Comment by ocefpaf** [comment]
> did you guys solve the dedupe or problem on Travis (iow pushing the same pr cancels the previous) which appveyor and circleci just do nicely

I am not on top of that b/c, I was mostly away the past moth, but at least `uritemplate` made it! Now I restarted https://travis-ci.org/conda-forge/google-api-python-client-feedstock/builds/208310251

**Comment by jreback** [comment]
thanks @ocefpaf that is proceeding

**Pull request merged**
